version: "3.8"

services:
  frontend:
    build:
      context: ./chat-room-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80" # Exponemos el puerto 3000 para el frontend en NGINX
    depends_on:
      - backend

  backend:
    build:
      context: ./chat-room-backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000" # Puerto para el backend en Express
    environment:
      - MONGO_URI=mongodb://mongodb:27017/mydatabase
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017" # Puerto estándar de MongoDB
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
